services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GalDigitalGmbh\Validation\Symfony:
    resource: '../../Symfony'
    exclude: '../../Symfony/{Exception,Traits}'
